---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "webserver.fullname" . }}-svc
  namespace: {{.Values.namespace}}
spec:
  selector:
    run: {{ template "webserver.fullname" . }}
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80