fullnameOverride: nginx-webserver
namespace: nginx
image:
  repo: jithinpnjm23/allex
  tag: ab5c83
replicas: '2'
resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi
service:
  type: LoadBalancer
